### PR TITLE
Routing missing slash

### LINKED ISSUE #111: Route plugin: Navigating to path without "/" prefix does not work
When navigating to a path with a `/` prefix, the page redirects correctly, but the `Route` component path does not render the correct component.

For example if I have

```tsx
const App = () => {
  return (
    <Container>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route path="/:username" component={Profile} />
        <Route component={NotFound} />
      </Switch>
    </Container>
  );
};
```

and somewhere in my app call this

```ts
dispatch(push)("username")
```
 
the NotFound component is rendered. However, when I refresh the page, the Profile component is rendered.

I can fix this by instead redirecting to

```ts
dispatch(push)("/username")
```

but ideally the user shouldn't need to do this

### PR DESCRIPTION
**Pull request by coffee-cup**
Closes #111 

- Update route example. It was a bit confusing before. Although now it might also be confusing, but for a different reason
- Normalize paths sent to push action. Right now this just ensures the path is prefixed with a `/`

### CODE REVIEW

File: examples/routing/src/pages/Home.tsx [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            },
+          }}
+        >
+          Wayne Gretzky
+        </Link>
+      </li>
+      <li>
+        <Link
+          to={{
+            path: "/ellon-musk",
```
Comment (andrejak) [inline examples/routing/src/pages/Home.tsx]:
```suggestion
            path: "/elon-musk",
```

File: packages/route-plugin/src/actions.ts [hunk 2]
```diff
@@ -8,13 +8,22 @@ import {
 } from "./types";
 import { createParamString } from "./utils";
 
+const normalizePath = (path: string): string =>
```
Comment (andrejak) [inline packages/route-plugin/src/actions.ts]: Some test cases for these might be good.

File: examples/routing/src/App.tsx [hunk 3]
```diff
@@ -1,29 +1,19 @@
...
+      <Redirect to="/home" />
+    </Route>
+
     <Switch>
-      <Route exact path="/user" component={UserPage} />
-      <Route exact path="/test" />
-      <Route component={HomePage} />
+      <Route exact path="/home" component={Home} />
+      <Route path="/:username" component={Profile} />
+      <Route component={NotFound} />
```
Comment (andrejak) [inline examples/routing/src/App.tsx]: If I go to /bla I don't hit Not Found. I guess that's expected since it could be a username? Should there be a check? same thing happens if I go to something more complex like /bla/bla/bla.
Screenshot 2019-09-26 at 17 08 43

File: examples/routing/src/pages/Home.tsx (hunk 1 above)
Comment (coffee-cup) [reply examples/routing/src/pages/Home.tsx]: lol

File: examples/routing/src/App.tsx (hunk 3 above)
Comment (coffee-cup) [reply examples/routing/src/App.tsx]: oh thats a good point, I'll move user profile stuff under `/user`
